sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: F6/+Yine+khZZzgSsSpO9ExOEsCtM3RIC0SzDGdnF93zGRScXQiQu+1MN0K9gcvYy+TcGYyxYSuoUef32X/DYGOoICBgoiUJriYETzgR6mWBBIVmNvIbJOhLXDmmK7p+qxBAqOH80Ce3WhNhf1/83/4Jzg1d+SDdaJFENMVsyFEMOdezKggPc7zJkydBfidVB2QjBLtwd5Rw9kOGWWB/lrmU+fCnXwE7So2/tb7O3DWq0XUwJxo/E9I+QZRr2mrMW7GtwsPQaYLdjSHVDL/F9mHiDVlDAgwfAfVXf6dXik5srZzZUPo5VDNu7JZJV6q5zwnbn+CdiBij3CzitcJ08c6zqKxJfYPlRPzjAKH+2/elfwI5+lMM9fQ2ejWXuIxcWmqhghNYZ9psjNTepeGIa9tOgo8ZaZkqf6LLyBASwCLdT8/OuEW8I8c7LvAXBK4HDeZXsNrOIUtoAo7YzDBKW1G6g26idbYahEgWsYyTm4ScFxL7dBQQLvgv2oeQCadsixBVD40kInTxw9bA8GDcRVsjjV4luGHCqlAyLcAiYd7LwpObx6Ua+lQQcykSEAIRu5ojzGpz2wUSgNJWF52XTpDgHG9DQBgyu5uxSAYQLPVKuwYVHE+aG/sW4hLcg+d6urHFwBAv8Qwl8B/OPIToagq+3VWThQ/mEi1iAs5lbZo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Twenty-Two-Goblins_2290
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy